name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '30 1 * * *'

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Get python version
        run: python -V
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-interaction
      - name: Run pytest
        run: poetry run pytest -vx --tb=native
